### ISSUE TITLE
AIY - Voicekit- Assistant version 0.1.0 volume is less than a whisper

### ISSUE THREAD

**Issue by sheridat** [googlesamples/assistant-sdk-python#145]
Your aware that some work has been done over on your "sister" repo google/aiyprojects-raspbian to update the voicekit to version 0.1.0 of the assistant.
The team has put together a fix https://github.com/google/aiyprojects-raspbian/pull/207

I've patched my system to take on that fix but there is a problem - the volume level of the assistant is not even as loud as a whisper. 

There are posts from users of the Raspberry.org AIY site who have updated to the new version of the assistant and they report the same issue - see https://www.raspberrypi.org/forums/viewtopic.php?f=114&t=200498

I've updated  https://github.com/google/aiyprojects-raspbian/pull/207 to advice accordingly.

**Comment by shivasiddharth** [comment]
The volume levels are low at the start after installation. "Hey google, set volume to maximum" command will increase the volume.

**Comment by sheridat** [comment]
@shivasiddharth yes there are some posts on the forum providing this solution as well https://www.raspberrypi.org/forums/viewtopic.php?f=114&t=200498&p=1249848#p1249848

**Comment by SzDavidHUN** [comment]
I've had this problem. The souliton above wasn't good enough, my speaker is a very sensitive thing, but it was still way too quiet. The problem was, that in alsamixer, the output was set 45 by defult. The command above, and *setting the volume to maximum in alsamixer* solved the problem really well.
I'm just leaving this answer here, maybe somebody will find it useful :)

**Comment by av4625** [comment]
When I ask the assistant to set the volume to maximum it just continually blinks and needs restarted
