### ISSUE TITLE
 Could not open file /var/lib/dpkg/status - open

### ISSUE THREAD

**Issue by captainpanther** [googlesamples/assistant-sdk-python#241]
i use the command below:
but have error

(env)root@imx7dsabresd:~# sudo apt-get install build-essential
Reading package lists... Error!
E: Could not open file /var/lib/dpkg/status - open (2: No such file or directory)
E: The package lists or status file could not be parsed or opened.

how to solve it?

**Comment by Fleker** [comment]
You're trying this on an imx7 running some version of Linux?

**Comment by captainpanther** [comment]
Yes,7.do you know how to solve it?

Nick <notifications@github.com> 於 2018年4月28日週六 01:44 寫道：

**Comment by Fleker** [comment]
It seems to be something to do with your Linux OS. Can you run `more /var/lib/dpkg/status`?

**Comment by captainpanther** [comment]
It cant show more.

Nick <notifications@github.com> 於 2018年4月28日週六 03:42 寫道：

**Comment by Fleker** [comment]
What error are you seeing in your terminal?

Can you run `cat /var/lib/dpkg/status`?

**Comment by captainpanther** [comment]
run command: cat /var/lib/dpkg/status

result:
cat: /var/lib/dpkg/status: No such file or directory

**Comment by Fleker** [comment]
That explains why the build tools are not installing, because your device is not reporting its information in a standard way. Unfortunately that makes the fix more challenging.

I searched for "Yocto /var/lib/dpkg/status" and came across [this StackOverflow post](https://stackoverflow.com/questions/35510734/why-is-var-lib-dpkg-status-missing-on-a-bitbake-generated-os). I hope that may be a good start to resolving your issue.
