### ISSUE TITLE
SDK guide notes

### ISSUE THREAD

**Issue by repoalpha** [googlesamples/assistant-sdk-python#251]
Nick here are the following observations taken from this guide
https://developers.google.com/assistant/sdk/guides/library/python/

1. "Configure a Developer Project and Account Settings" section. Down the page "Click the Device registration box." For what? You do nothing, with that device registration box at that point of the process. It then jumps to enable API. Both spawn tabs but its gets messy. The registration box is used later in the process it should be highlighted when its needed.

2. "Set Up Hardware and Network Access" you select Ubuntu (and again on the next section) but later pages it just seems to all merge into one document. You don't know what is for what even though Pi is labeled in places later its not clear did I hit the wrong link? What happened to Ubuntu or Pi am I on the correct path for this guide?

3. "Register the Device Model" then "Edit the model" then "To download the credentials file again, click the ellipses." could say "if you need to down load credentials.json again". Needs to be clear this is not an instruction.

4."Install the SDK and Sample Code". Python3. venv can be an issue on Ubuntu, you could link to alternatives like anconda for example. I had to use that. Its an unwanted distraction when it does not work.

5. "Generate credentials". The key point missing here especially if you flick back and forth later is that you are using a credentials.json file downloaded from the browser earlier under device registration / register model to create another credentials.json file using a URL which is then placed in a hidden directory /.config/google-oauthlib-tool/. That part is not clear you have two files of the same name on this guide, skip a section or come back later its confusing.

6. "Register Custom Device Actions" then "Create an Action Package". This is where the wheels fall off. There is already an actions file in the ~/assistant-sdk-python/google-assistant-sdk/ directory, which you need to in this case (since we are following the guide) copied over to '
library' directory. The example cp command should be like:

cp ~/assistant-sdk-python/google-assistant-sdk/actions.json ~/ assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/library/

That then places the copied action file next to hotword.py ready for use. Otherwise you get errors later on using hotword.py in that the google assistant works and takes commands but the action does not occur. The error looks like this from hotword.py

"This device is not registered. This means you will not be able to use
    Device Actions or see your device in Assistant Settings. In order to
    register this device follow instructions at:

    https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device"

7. "Deploy the Action Package". In this instance it would be better to download or wget the actions package  into  ~/ assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/library/

8. I would highlight if you need the model ID when using commands that need model ID to get it from https://console.actions.google.com your project  under "device registration" click on your model copy the model ID, same with project right click gear under select project, copy project ID.

9. A flow diagram would really help show the common build steps and the customised or build you own actions steps so you can see how it all bolts together where the branches are. Its a new vernacular to learn for anyone starting out, it make sense to insiders but not others as to what fits where.

**Comment by irataxy** [comment]
Thank you for submitting this. We value your feedback!!

> "Configure a Developer Project and Account Settings" section. Down the page "Click the Device registration box." For what? You do nothing, with that device registration box at that point of the process. It then jumps to enable API. Both spawn tabs but its gets messy. The registration box is used later in the process it should be highlighted when its needed.

Fixed. You still need to enable the API in GCP, but we are looking at improving this flow.

> "Set Up Hardware and Network Access" you select Ubuntu (and again on the next section) but later pages it just seems to all merge into one document. You don't know what is for what even though Pi is labeled in places later its not clear did I hit the wrong link? What happened to Ubuntu or Pi am I on the correct path for this guide?

The hardware/network access and audio topics are hardware-specific pages. I added a line of text to note this near the top. The rest of the pages are generally hardware-agnostic, but you will see some references to the Raspberry Pi since it has accessible GPIO ports that we wanted to use for demonstration purposes. 

> "Register the Device Model" then "Edit the model" then "To download the credentials file again, click the ellipses." could say "if you need to down load credentials.json again". Needs to be clear this is not an instruction.

Fixed

> 4."Install the SDK and Sample Code". Python3. venv can be an issue on Ubuntu, you could link to alternatives like anconda for example. I had to use that. Its an unwanted distraction when it does not work.

I like the idea of listing alternatives, but unfortunately we don't have the bandwidth to support these alternatives.

> "Generate credentials". The key point missing here especially if you flick back and forth later is that you are using a credentials.json file downloaded from the browser earlier under device registration / register model to create another credentials.json file using a URL which is then placed in a hidden directory /.config/google-oauthlib-tool/. That part is not clear you have two files of the same name on this guide, skip a section or come back later its confusing.

I agree this is confusing. I added some clarification text and we have other improvements in the works.

> "Register Custom Device Actions" then "Create an Action Package". This is where the wheels fall off. There is already an actions file in the ~/assistant-sdk-python/google-assistant-sdk/ directory, which you need to in this case (since we are following the guide) copied over to '
> library' directory. The example cp command should be like:
> 
> cp ~/assistant-sdk-python/google-assistant-sdk/actions.json ~/ assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/library/
> 
> That then places the copied action file next to hotword.py ready for use. Otherwise you get errors later on using hotword.py in that the google assistant works and takes commands but the action does not occur. The error looks like this from hotword.py
> 
> "This device is not registered. This means you will not be able to use
> Device Actions or see your device in Assistant Settings. In order to
> register this device follow instructions at:
> 
> https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device"

I'd like to better understand this. The sample action package does not need to be copied to the /library directory. In fact, the entire "Create an Action Package" section need not be done on the device. As long as you supply the path to the action package json file and the project ID to the gactions binary, it should work fine. The error from the hotword.py file is unrelated.

> "Deploy the Action Package". In this instance it would be better to download or wget the actions package into ~/ assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/library/

I added a step to the top of the page to `cd` into this directory. I fear if I add `wget` and a URL, it will trip up users since the gactions binary is OS and architecture dependent.

> I would highlight if you need the model ID when using commands that need model ID to get it from https://console.actions.google.com your project under "device registration" click on your model copy the model ID, same with project right click gear under select project, copy project ID.

This method of getting the project ID is called out on https://developers.google.com/assistant/sdk/guides/library/python/embed/run-sample. I'm not too worried about the model ID, since you would have that in the command history from running the sample (although I admit you may lose this on later runs). 

> A flow diagram would really help show the common build steps and the customised or build you own actions steps so you can see how it all bolts together where the branches are. Its a new vernacular to learn for anyone starting out, it make sense to insiders but not others as to what fits where.

We are thinking of adding a blog post for this.

**Comment by RaykPlatzek** [comment]
@irataxy just tryed to setup a new project and register a model using your registration UI. Followed all the steps...however, the Device registration box does not appear at all. Not sure if this is related to any of the changes ? Just came across this issue and it seems likely. Thanks for clarification.

**Comment by irataxy** [comment]
If you create a new project in the AoG Console and scroll to the very bottom of the page, you should see the Device registration box under **More options**.

If you choose Skip instead of selecting the Device registration box or navigate away from the page and come back later, it looks like you now can't access the Device registration tab (under ADVANCED OPTIONS) from the left navbar. This is a bug; I'll follow up on this.

**Comment by RaykPlatzek** [comment]
Thanks for looking into it.
