### ISSUE TITLE
How to trigger Google assistant by 'holding a button to record then release it when finish'?

### ISSUE THREAD

**Issue by tiancaipipi110** [googlesamples/assistant-sdk-python#270]
How can I trigger Google assistant by 'holding a button to record then release it when finish' or 'button press' instead of 'ok google' voice trigger? My button is at GPIO 18.

Which file should I modify or can they be modified?

**Comment by Fleker** [comment]
Right now the sample waits for the [END_OF_UTTERANCE[(https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py#L141) event, but you can directly close the `Assist` gRPC event in order to indicate that you want to stop the request manually.
