### ISSUE TITLE
How to get assistant's response text?

### ISSUE THREAD

**Issue by krsnaa** [googlesamples/assistant-sdk-python#78]
ConverseResponse.result.spoken_response_text is always blank in the grpc sample.

**Comment by gauravsacc** [comment]
see here https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha1#google.assistant.embedded.v1alpha1.ConverseResult 
spoken_response_text	- This is only returned for an IFTTT action.

**Comment by krsnaa** [comment]
Is there a reason it is not supported for non-IFTTT actions?

**Comment by proppy** [comment]
@krsnaa feel free to discuss this topic w/ the team in the [Google+ community](http://g.co/assistantsdkdev).

A few pointer to similar discussion in the past:
https://plus.google.com/112935559604288840722/posts/aufnsN9uCvN
https://plus.google.com/+Mart%C3%ADPlanellas/posts/eoQbWzemQvd
https://plus.google.com/101852559274654726533/posts/BskrFscRYdh

**Comment by nagen1** [comment]
Hi, 
is it still the case we have to use IFTTT for getting text response !? or we can do it with api.ai webhook (google cloud Functions)

I tried doing multiple options, however there is something or other issues coming up. wondering how to fix those :)

1. tried picking up query when use says something and parse it and execute local function (Turn on LEDs) - with this I am able to get things done, but not in interpretative way as my local functions are executing no query not the response from home assistant

2. I tried with https://github.com/api-ai/apiai-python-client - I was able to send query to api.ai and get response back with from my action and able to run my local functions based on api.ai response, However, google home responds with different results for query. Since execution logic not depended response from google home it's not user friendly.

3. Trying to figure out how this webhook works and do we have to use webhooks !?? wondering.

As I was started researching more got to see this IO demo/info where they talked about user talks to Microwave and it turns on since it has Assistant SDK installed native. However, they didn't showed the demo of it. 

**Problem statement :** I am trying to solve is.., I have RPi, installed Assistant SDK (works great) and now I would like to control connected hardware to it based on google home response. 

Any suggestions much appreciated.

**Comment by imsunburnt** [comment]
Here is a code snippet from a modified hotword.py sample.  

You can get the spoken text from event.args["text"]

def process_event(event, assistant):
    """Pretty prints events.

    Prints all events that occur with two spaces between each new
    conversation and a single space between turns of a conversation.

    Args:
        event(event.Event): The current event to process.
    """
    print(event)

    if event.type == EventType.ON_RECOGNIZING_SPEECH_FINISHED:
        speech_text = event.args["text"]
        print("speech text: " + speech_text)
        # here is where we add our code
        if "some command" in speech:
            # do this if you don't want to play the conversation response
            assistant.stop_conversation()
            # then do some custom action

def main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('--credentials', type=existing_file,
                        metavar='OAUTH2_CREDENTIALS_FILE',
                        default=os.path.join(
                            os.path.expanduser('~/.config'),
                            'google-oauthlib-tool',
                            'credentials.json'
                        ),
                        help='Path to store and read OAuth2 credentials')
    args = parser.parse_args()
    with open(args.credentials, 'r') as f:
        credentials = google.oauth2.credentials.Credentials(token=None,
                                                            **json.load(f))

    with Assistant(credentials) as assistant:
        for event in assistant.start():
            process_event(event, assistant)


if __name__ == '__main__':
    main()

**Comment by Fleker** [comment]
`supplemental_display_text` can now be retrieved for all responses from the Assistant.

**Comment by Flowdeeps** [comment]
Sorry to be the threadromancer here but is there any documentation on `supplemental_display_text`?

**Comment by Fleker** [comment]
The documentation for [supplemental display text](https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha2#google.assistant.embedded.v1alpha2.DialogStateOut) is available, as well as for [SpeechRecognitionResult](https://developers.google.com/assistant/sdk/reference/rpc/google.assistant.embedded.v1alpha2#google.assistant.embedded.v1alpha2.SpeechRecognitionResult).

At the same time, it does seem like you'd be better off going with a [custom device action](https://developers.google.com/assistant/sdk/device-actions-overview).

**Comment by gerardwr** [comment]
Custom device action work nicely on RPi.

Several standard device types are supported, but it is not possible to add your own custom device.

And, as I see it, it is not possible to configure more than 1 device of as specific type, So only 1 light, 1 switch.

But for a simple application it works nicely.

**Comment by Flowdeeps** [comment]
I'm not actually controlling any external devices, I just need to be able to receive assistant responses for parsing as part of another function. I can't see any code examples to try out and I'm not proficient enough in Python yet to know what's likely to work.

**Comment by sharkwheels** [comment]
Sorry to jump in, but just to clarify: Google does not allow you to get spoken_response_text unless you use IFTTT. But now  spoken_response_text will be included in the supplemental_display_text ? am I understanding that correctly? Thanks.

**Comment by Fleker** [comment]
Yes we are now sending back the response text to the developer. The IFTTT limitation was true a year ago but the feature was added in December.

**Comment by Fleker** [comment]
All of our samples have been updated to include getting the text output and printing it.

**Comment by jordancoult** [comment]
@Fleker Sorry to add more to this thread, but is there a sure way to retrieve a text response that's always identical to the speech spoken in AssistResponse.audio_out? The doc for supplemental_display_text says that the text may be "additional information which aids the user's understanding" instead of the spoken output.

**Comment by Fleker** [comment]
Text output is available in both the service and library.

It is not necessarily going to be identical to the audio output. Certain queries made on a phone, for example, will return different audio than text. The text may have more or less detail than the audio.

**Comment by jordancoult** [comment]
@Fleker Thanks for the response. I'm still trying to get the text response with the library. How would we go about retrieving dialogstateout in--for example--the hotword.py sample?

**Comment by Fleker** [comment]
It wouldn't be in the same API structure. It should be returned as an event with the text as a parameter.

**Comment by michellemxm** [comment]
I am developing with AIY voice kit v2, and trying to get Assistant's response in text format. I am using aiy.assistant.library but could not find a way to get the text properly with supplemental_display_text. Is there any sample code or documentation that I can refer to? I am not proficient in Python...

As per what you said 'it should be returned as an event with the text as a parameter', are you referring to ON_RENDER_RESPONSE? The text parameter I got from this is always empty...
