### ISSUE TITLE
Implementing custom actions (actions.py)

### ISSUE THREAD

**Issue by yuvalsegev** [googlesamples/assistant-sdk-python#90]
Hi all! Iv'e used [this ](https://developers.google.com/assistant/sdk/prototype/getting-started-pi-python/) guide to bulild the assistant on a Pi, now i'd like to add my own custom actions like shown [here](https://aiyprojects.withgoogle.com/voice#makers-guide-3-3--create-a-new-voice-command-or-action)

But a can't find the `action.py` file, I believe because the AIY Voice kit isn't using the exact same code..

Is there any way I can add custom action with a python code?

**Comment by thomas-vl** [comment]
Hi what happens if you go to the terminal and type:
CD ~/voice-recognizer-raspi/src/
And then do:
LS

**Comment by proppy** [comment]
@yuvalsegev this is more of a question for the https://github.com/google/aiyprojects-raspbian repo.

This repository is for tracking issues about the Google Assistant SDK samples.

**Comment by mmgill** [comment]
I had the same issue.  Had to use the https://github.com/google/aiyprojects-raspbian repo to add custom commands.  Open action.py and follow the examples to accept voice input to control device/pins.  I was able to send IR commands easily, and I have little python experience. 

I wish it was available in the googlesamples repo tho since the Alexa/Google Assistant combo is based on this sdk.. oh well

**Comment by aycgit** [comment]
you should add a local custom command feature for this repo too, it would speed up most of my commands a lot

**Comment by Fleker** [comment]
We've added support for device actions for on-device fulfillment.
