### ISSUE TITLE
Welcome message on startup

### ISSUE THREAD

**Issue by HarvsG** [googlesamples/assistant-sdk-python#92]
Is there a way to enable a spoken welcome message on startup?

**Comment by TheNameIsEaston** [comment]
Either a message or a startup tone would be very helpful.

**Comment by bkbilly** [comment]
If you mean after you say the hotword "hey google" or "ok google" then it is very easy.
You should edit the file `hotword.py` file located here: `env/lib/python3.4/site-packages/googlesamples/assistant/library`
Then at `if event.type == EventType.ON_CONVERSATION_TURN_STARTED:` add the following code:
`subprocess.Popen(["aplay", "/home/pi/mywav.wav"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)` where mywav.wav is your sound file you want to play.

**Comment by boegi** [comment]
I play a startup wav sound in the __main__.py 
(directly after the start of the PI because I also autostart the assistant)

one line bellow... def main(): I added playstarted()
```
def main():
    playstarted()
```

and here is my playstarted...  I have to mention, that I'm a beginner to python - and this is my workaround I want to share. I guess this is not the best way to do it.
```
def playstarted():
    #print("Init PySound")
    import pygame
    import time
    #print("Playing Start Sound")
    pygame.init()
    pygame.mixer.music.load("/home/pi/env/lib/python3.4/site-packages/google/assistant/sounds/google_assistant_starting2.wav")
    pygame.mixer.music.play()
    time.sleep(10)
    #print("finished start sound")
    pygame.quit()
```
I had some problems with the Sound HW beeing blocked by the wav sound. That is the reason for the pygame.quit() and the sleep(10)

Maybe this is not a problem with the subprocess method mentioned by bkbilly.

BTW. in the mentioned library folder there is another file I do not remember right now. (Not the events.py) but in there you can also play the start sound on "start" of the Assistant.

PS: Be sure to backup the files before upgrading to the new version. (Update was released today - I had to restore a backup)

**Comment by olskar** [comment]
@bkbilly I get the following error when trying to use your code

`
LED on
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/new-project/hotword.py", line 84, in <module>
    main()
  File "/home/pi/new-project/hotword.py", line 80, in main
    process_event(event)
  File "/home/pi/new-project/hotword.py", line 51, in process_event
    subprocess.Popen(["aplay", "/home/pi/mywav.wav"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
NameError: name 'subprocess' is not defined
`

**Comment by Fleker** [comment]
Closing this issue as it seems like a solution is posted in the comments.
